### PR TITLE
parse "set timestamp" statement and use it as query timestamp

### PR DESCRIPTION
**Pull request by Trane9991**
Some slow query log entries don't have the `# Time` line, however many have the `SET timestamp=....;`, which can be used as query timestamp.

This PR implements parsing of the `SET timestamp=...;` expression and uses it as event time if it is missing.

### CODE REVIEW

**Comment by Trane9991** [comment]
Hey @percona-csalguero, thanks for the review,
bu I don't have permission to merge this.

Are you still running some tests around the change, or this can be merged?

Thanks!

**Comment by Trane9991** [comment]
@percona-csalguero any chance to merge this? :)

**Comment by Trane9991** [comment]
@percona-csalguero @BupycHuk  lets merge this, maybe?

**Comment by lorddang** [comment]
this can be merged?

**Comment by Trane9991** [comment]
I hope so.
Folks from percona approved it but didn't merge.
And I do not have permissions to merge. Can't get any response since  :(

**Review by percona-csalguero — APPROVED** [review]

**Review by BupycHuk — APPROVED** [review]

**Pull request merged**
