### PR TITLE
PMM-4186 bsd 3 re-license

### PR DESCRIPTION
**Pull request by michaelcoburn**
Converting AGPLv3 to BSD-3 for the project.

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/go-mysql?pullRequest=48) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/go-mysql?pullRequest=48) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/go-mysql?pullRequest=48) it.</sub>

**Comment by michaelcoburn** [comment]
I might have also gotten our official company name wrong - I used "Percona" but it may be "Percona LLC". If so we'd need to update LICENSE and README.md accordingly.

**Comment by AlekSi** [comment]
>I might have also gotten our official company name wrong - I used "Percona" but it may be "Percona LLC". If so we'd need to update LICENSE and README.md accordingly.

Who can answer that?

Also, we probably should do that change in PMM-2.0 branch, not in master.

**Comment by michaelcoburn** [comment]
> I might have also gotten our official company name wrong - I used "Percona" but it may be "Percona LLC". If so we'd need to update LICENSE and README.md accordingly.

I'm asking Legal team
https://percona.atlassian.net/servicedesk/customer/portal/2/HD-6476

**Comment by michaelcoburn** [comment]
> > I might have also gotten our official company name wrong - I used "Percona" but it may be "Percona LLC". If so we'd need to update LICENSE and README.md accordingly.
> 
> I'm asking Legal team
> https://percona.atlassian.net/servicedesk/customer/portal/2/HD-6476

Proper name we must use is **Percona, LLC**

**Pull request merged**
