### PR TITLE
PMM-2859: Add new feature to record "Last read offset"

### PR DESCRIPTION
**Pull request by gywndi**
Hi, 

Thanks to your good contribution, I was able to easily access mysql slowlog parsing based on Go.
But, when I tested on my environment, I found that the time was not parsed normally. Additionally, I have one more requirement to record the last processed file position. (Start is offset, but end is how?)

My aim is, a collection process parse slow log from the last read position(LastOffset) it processed, periodically.

1. Fixed a problem where the time was not parsed as normal by changing the regular expression.
2. Fixed an issue where Offset was not logged normally in case of the last slow log event.

My test file is shown below.
```
# Time: 2017-12-13T02:41:18.673330Z
# User@Host: test[test] @  [127.0.0.1]  Id:    17
# Schema: test  Last_errno: 0  Killed: 0
# Query_time: 1.000249  Lock_time: 0.000000  Rows_sent: 1  Rows_examined: 0  Rows_affected: 0
# Bytes_sent: 89  Tmp_tables: 0  Tmp_disk_tables: 0  Tmp_table_sizes: 0
# QC_Hit: No  Full_scan: No  Full_join: No  Tmp_table: No  Tmp_table_on_disk: No
# Filesort: No  Filesort_on_disk: No  Merge_passes: 0
SET timestamp=1513132878;
select 1
# Time: 2017-12-13T02:41:18.673330Z
# User@Host: test[test] @  [127.0.0.1]  Id:    17
# Schema: test  Last_errno: 0  Killed: 0
# Query_time: 1.000249  Lock_time: 0.000000  Rows_sent: 1  Rows_examined: 0  Rows_affected: 0
# Bytes_sent: 89  Tmp_tables: 0  Tmp_disk_tables: 0  Tmp_table_sizes: 0
# QC_Hit: No  Full_scan: No  Full_join: No  Tmp_table: No  Tmp_table_on_disk: No
# Filesort: No  Filesort_on_disk: No  Merge_passes: 0
SET timestamp=1513132878;
select 2
# Time: 2017-12-13T02:41:18.673330Z
# User@Host: test[test] @  [127.0.0.1]  Id:    17
# Schema: test  Last_errno: 0  Killed: 0
# Query_time: 1.000249  Lock_time: 0.000000  Rows_sent: 1  Rows_examined: 0  Rows_affected: 0
# Bytes_sent: 89  Tmp_tables: 0  Tmp_disk_tables: 0  Tmp_table_sizes: 0
# QC_Hit: No  Full_scan: No  Full_join: No  Tmp_table: No  Tmp_table_on_disk: No
# Filesort: No  Filesort_on_disk: No  Merge_passes: 0
SET timestamp=1513132878;
select 3
# Time: 2017-12-13T02:41:18.673330Z
# User@Host: test[test] @  [127.0.0.1]  Id:    17
# Schema: test  Last_errno: 0  Killed: 0
# Query_time: 1.000249  Lock_time: 0.000000  Rows_sent: 1  Rows_examined: 0  Rows_affected: 0
# Bytes_sent: 89  Tmp_tables: 0  Tmp_disk_tables: 0  Tmp_table_sizes: 0
# QC_Hit: No  Full_scan: No  Full_join: No  Tmp_table: No  Tmp_table_on_disk: No
# Filesort: No  Filesort_on_disk: No  Merge_passes: 0
SET timestamp=1513132878;
select 4
```

The event results received are as follows.
```
&{0 463 2017-12-13T02:41:18.673330Z false select 1 test  test map[Query_time:1.000249 Lock_time:0] map[Rows_examined:0 Tmp_tables:0 Merge_passes:0 Tmp_table_sizes:0 Last_errno:0 Killed:0 Rows_sent:1 Rows_affected:0 Bytes_sent:89 Tmp_disk_tables:0] map[Tmp_table_on_disk:false Filesort:false Filesort_on_disk:false QC_Hit:false Full_scan:false Full_join:false Tmp_table:false]  0}
&{464 926 2017-12-13T02:41:18.673330Z false select 2 test  test map[Query_time:1.000249 Lock_time:0] map[Merge_passes:0 Killed:0 Rows_sent:1 Rows_examined:0 Tmp_tables:0 Tmp_disk_tables:0 Tmp_table_sizes:0 Last_errno:0 Rows_affected:0 Bytes_sent:89] map[Full_join:false Tmp_table:false Tmp_table_on_disk:false Filesort:false Filesort_on_disk:false QC_Hit:false Full_scan:false]  0}
&{927 1389 2017-12-13T02:41:18.673330Z false select 3 test  test map[Lock_time:0 Query_time:1.000249] map[Last_errno:0 Killed:0 Rows_sent:1 Rows_affected:0 Bytes_sent:89 Tmp_table_sizes:0 Merge_passes:0 Rows_examined:0 Tmp_tables:0 Tmp_disk_tables:0] map[Full_scan:false Full_join:false Tmp_table:false Tmp_table_on_disk:false Filesort:false Filesort_on_disk:false QC_Hit:false]  0}
&{1390 1852 2017-12-13T02:41:18.673330Z false select 4 test  test map[Query_time:1.000249 Lock_time:0] map[Last_errno:0 Killed:0 Rows_sent:1 Bytes_sent:89 Tmp_disk_tables:0 Tmp_table_sizes:0 Rows_examined:0 Rows_affected:0 Tmp_tables:0 Merge_passes:0] map[Filesort:false Filesort_on_disk:false QC_Hit:false Full_scan:false Full_join:false Tmp_table:false Tmp_table_on_disk:false]  0}
```
By the way, what is the offset used for? I want to put the last processing position in the offset.

Best regards,
Chan.

### CODE REVIEW

**Comment by gywndi** [comment]
It is for reprocessing after the last recorded file position.
Thanks.
Chan.

**Comment by arvenil** [comment]
Hi @gywndi 
I would like to understand your request - could you put a bit more context what are your trying to achieve?

1. The time format in your sample is indeed different from what we expect. From which MySQL version it comes from? You can check some samples we collected https://github.com/percona/go-mysql/tree/master/test/slow-logs and as you can see they have different format. We can't drop parsing that format as it would brake parsing logs for those samples.
2. Are you trying to parse slow log file outside of PMM?
3. Are you trying to process slowlog file that is at the same time appended with new entries? Which function did you use? Could you share some code? To get LastOffset you can use `Seek(0, os.SEEK_CUR)` on opened file `*os.File` or if for some reasons you brake earlier you can use `event.Offset` as `LastOffset`. https://github.com/percona/qan-agent/blob/master/qan/analyzer/mysql/worker/slowlog/worker.go#L308-L315

**Comment by gywndi** [comment]
Hi Arvenil,

1. From which MySQL version it comes from? 
=> Percona Server for MySQL 5.7.22, If there is no time input, does QAN put the current time?

2. Are you trying to parse slow log file outside of PMM?
=> I want to save it as a separate log server other than mysql in PMM. I am thinking about the way that the program finishes reading from the last processed position to the end of the file and saving.

3. Are you trying to process slowlog file that is at the same time appended with new entries? ...
=> I want to collect the slow data by executing program every 5 minutes. To consider situations that could affect your network when too much of a slow stack is being built, I just want to be notified by the administrator not collect them. The sample is below.
```
func main(){
	file, err := os.Open(*slowlogFile)
	if err != nil {
		continue
	}

	// read last offset from position file
	.... code .....

	// check size, if size too big, skip and send alarm to DBA
	.... code .....

	p := slow.NewSlowLogParser(file, log.Options{StartOffset: offset, Debug: false})
	go p.Start()
	for e := range p.EventChan() {
		// API call 
		.... code .....

		offset = e.LastOffset
	}
	file.Close()

	// write the last offset on position file
	.... code .....
}
```
I used event.Offset, but this value is considered to be the one that stores the starting point of the slow query. In other words, if collection stops in the middle, I can not start the last executed position.

**Comment by arvenil** [comment]
@gywndi `offset = file.Seek(0, os.SEEK_CUR)`, would that work for you?
```golang
func main(){
	file, err := os.Open(*slowlogFile)
	if err != nil {
		continue
	}

	// read last offset from position file
	.... code .....

	// check size, if size too big, skip and send alarm to DBA
	.... code .....

	p := slow.NewSlowLogParser(file, log.Options{StartOffset: offset, Debug: false})
	go p.Start()
	for e := range p.EventChan() {
		// API call 
		.... code .....

		offset = file.Seek(0, os.SEEK_CUR)
	}
	file.Close()

	// write the last offset on position file
	.... code .....
}
```

**Comment by gywndi** [comment]
@arvenil Thanks for great reply.

I tested it with code you gave me, and result is below. 
The leading digit is Offset from "file.Seek (0, os.SEEK_CUR)", last file offset position.
```
2315 {"Offset":0,"LastOffset":463,..}
2315 {"Offset":464,"LastOffset":926,..}
2315 {"Offset":927,"LastOffset":1389,..}
2315 {"Offset":1390,"LastOffset":1852,..}
2315 {"Offset":1853,"LastOffset":2315,..}
```
What I want to do is to reprocess the failed part if it fails during file processing. If it fails during the 1389 offset process, it will miss the slow log between 1390 and 2315.

Anyway, have you made any changes to the timestamp format in mysql5.7?
(ex, Time: 2017-12-13T02:41:18.673330Z)

**Comment by arvenil** [comment]
Hi @gywndi,

1. I checked it out and `file.Seek (0, os.SEEK_CUR)` also didn't work for me, sorry about that. According to doc it should work but I think the issue might be using `bufio` to read from file (maybe reads from file and buffers data). I could try to get rid of that but also your solution to use `p.bytesRead` works. I've used your idea, fixed some corner cases and updated tests - seems to work.
2. About timestamp. Indeed the format changed in newer MySQL. I've added both methods of parsing to keep backward compatibility for older MySQL versions. Also I've changed the type of `Ts` to `time.Time` in order to hide this inconsistency in formats.

Could you please?
- [ ] Verify if pull request #39 satisfies your request 
- [ ] Sign CLA so we could include your contribution

**Comment by gywndi** [comment]
Hi~

In my opinion, time zone issues are likely to occur in the old format. Unlike the new format, it does not include a time zone infomation in it.

So what if you change this part as below?

### AS-IS
```
if len(m) == 2 {
	p.event.Ts, _ = time.Parse("060102 15:04:05", m[1])
} else {
	m = timeNewRe.FindStringSubmatch(line)
	if len(m) == 2 {
		p.event.Ts, _ = time.Parse(time.RFC3339Nano, m[1])
	} else {
		p.event.Ts = time.Time{}
		return
	}
}
```

### TO-BE
```
if len(m) == 2 {
	p.event.Ts, _ = time.ParseInLocation("060102 15:04:05", m[1], time.Local)
} else {
	m = timeNewRe.FindStringSubmatch(line)
	if len(m) == 2 {
		p.event.Ts, _ = time.ParseInLocation(time.RFC3339Nano, m[1], time.Local)
	} else {
		p.event.Ts = time.Time{}
		return
	}
}
```
If the column type of the database is TIMEZONE, I think that there is no issue in data storage.
If there's no problem with this code, I want to work with this library this included.

Thanks.
Chan.

**Pull request merged**
