### PR TITLE
PMM-1989: fix panic

### PR DESCRIPTION
**Pull request by arvenil**
This merges #13 and #22

### CODE REVIEW

**Comment by rnovikovP** [comment]
@tfukaya  ,  @xuewindy  can you sign our Contributor License Agreement (by clicking the button above) to help us merge your PRs. Thanks for helping us!

**Comment by tfukaya** [comment]
Thanks!
I will confirm my company to agree the CLA.
Please wait a moment.

**Comment by tfukaya** [comment]
@rnovikovP 
I just signed the CLA.
Thanks.

**Comment by arvenil** [comment]
@xuewindy Could you sign the CLA?

**Pull request closed without merging**
