### PR TITLE
when parsing log, why not use the 3rd group of the regex as the host?

### PR DESCRIPTION
**Pull request by running-tomato**
i wonder why not take the index(3) as the Host, now the code takes the 2nd matched group as the Host field.

```
     userRe    = regexp.MustCompile(`User@Host: ([^\[]+|\[[^[]+\]).*?@ (\S*) \[(.*)\]`)
//snip
	} else if strings.HasPrefix(line, "# User") {
		if p.opt.Debug {
			l.Println("user")
		}
		m := userRe.FindStringSubmatch(line)
		if len(m) < 3 {
			return
		}
		p.event.User = m[1]
		p.event.Host = m[3]

```

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/go-mysql?pullRequest=45) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/go-mysql?pullRequest=45) before we can accept your contribution.<br/><hr/>**wuguoquan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/go-mysql?pullRequest=45) it.</sub>

**Comment by percona-csalguero** [comment]
Don't we have a tests for this?

**Comment by quan0012** [comment]
i'm not familiar with the step how to launch a pull request on github, this is my first PR, meanwhile, forgive my poor English. something confused me,
1.  i want to know is it right to change the index 2->3?  
2.  > Don't we have a tests for this?
does this mean I should write or update a unit test for this PR? if the answer of first question is Yes, i am happy to add a test for it.

I want to know how do you think of this index-change

**Comment by quan0012** [comment]
if I write a unit test, which is the best way to make sure all tests can pass?
i know when i push the commit to github then travis will run the tests for me, and i will know whether my code working well,
but how can i run local to make sure everything is ok before pushing the commit, because i am not want to disturb you when I pushed a wrong commit

**Comment by quan0012** [comment]
@percona-csalguero  can you help me review this PR?

**Comment by percona-csalguero** [comment]
Added a test case in https://github.com/percona/go-mysql/pull/46

**Pull request merged**
